#!/bin/sh

ProgName=$(basename $0)
  
sub_help(){
    echo "Usage: $ProgName <subcommand> [options]\n"
    echo "Subcommands:"
    echo "    version"
    echo "    update"
    echo ""
}
  
sub_version(){
    cat ~/dotfiles/VERSION
}
  
sub_update(){
    cd ~/dotfiles && git pull && ./install.sh
    echo "-----"
    echo "dotfiles is now version `sub_version`"
}
  
subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        sub_${subcommand} $@
        if [ $? = 127 ]; then
            echo "Error: '$subcommand' is not a known subcommand." >&2
            echo "       Run '$ProgName --help' for a list of known subcommands." >&2
            exit 1
        fi
        ;;
esac